'use strict';

const DEVICE_ROOT = 'devices';
const STATE_TEMPERATURE = 'temperature';
const STATE_RELATIVE_HUMIDITY = 'relativeHumidity';
const STATE_ABSOLUTE_HUMIDITY = 'absoluteHumidity';
const STATE_DEW_POINT_TEMPERATURE = 'dewPointTemperature';
const CARD_HEADER_BACKGROUND = '#0f4c81';
const OUTDOOR_CARD_HEADER_BACKGROUND = '#21867a';
const ADAPTER_ICON = 'adapter/absolutehumidity/absolutehumidity.svg';

module.exports = {
	ADAPTER_ICON,
	CARD_HEADER_BACKGROUND,
	DEVICE_ROOT,
	OUTDOOR_CARD_HEADER_BACKGROUND,
	STATE_ABSOLUTE_HUMIDITY,
	STATE_DEW_POINT_TEMPERATURE,
	STATE_RELATIVE_HUMIDITY,
	STATE_TEMPERATURE,
};
